### ISSUE TITLE
Matrix rename to RealMatrix

### ISSUE THREAD

**Issue by b3liever** [b3liever/manu#2]
The Matrix object is only meant to support real numbers, hence the lack of generics. Should we follow the paradigm of Apache commons math and call it RealMatrix?

**Comment by xflywind** [comment]
What is this package for? If can't support complex number, then how to implement fft?
So the package isn't meant to scientific calculation, especially in speech analysis？

**Comment by b3liever** [comment]
No, exactly it doesn't support complex numbers, say so in the readme. There are other packages that support them i.e. https://github.com/twist-vector/matrix

**Comment by b3liever** [comment]
> What is this package for? If can't support complex number, then how to implement fft?
> So the package isn't meant to scientific calculation, especially in speech analysis？

You know I can't argue with you, go find something else.

**Comment by b3liever** [comment]
Too late to rename anything
