### ISSUE TITLE
Should I remove "broadcasting"?

### ISSUE THREAD

**Issue by b3liever** [b3liever/manu#3]
In this lib, I implemented an non-standard way to do broadcasting between matrices of non matching dimensions. It kind of abuses a nim language feature of ``distinct`` types to overload matrix math operators with versions that "broadcast". It works fine, but I am unsure of its usefulness.

Pros:
- no bugs in it
- works at compile time, no overhead
- explicit, you need to cast variables to ``ColumnVector``, ``RowVector`` right when you perform an op.

Cons:
- explodes code size of ``matrix.nim``
- non standard way
- might confuse/annoy some people

Dear reader/users of this lib, what do you think?

**Comment by mratsim** [comment]
Do you have example of broadcast that you find questionable?

**Comment by b3liever** [comment]
I dunno, I guess I let it be.
